package com.example.moztrivia.util

import androidx.compose.ui.graphics.Color

object AppColors {
//    val mLightGray = Color(0xffb4b9cd)
//    val mBlack = Color(0xff060814)
    val mOffWhite = Color(0xffeceeef)
//    val mLightPurple = Color(0xff545a75)
//    val mGreen = Color(0xff159F8A)
//    val mOffDarkPurple = Color(0xFF22496B)
//    val mLightBlue = Color(0xff127EEA)
//    val mBrown = Color(0xff7f6749)
//    val mBlue  = Color(0xff4b5f9e)
    val mYellow = Color(0xfffcba03)
    val mRed= Color.Red


    val md_theme_light_primary = Color(0xFF006397)
    val md_theme_light_onPrimary = Color(0xFFFFFFFF)
    val md_theme_light_primaryContainer = Color(0xFFCCE5FF)
    val md_theme_light_onPrimaryContainer = Color(0xFF001D31)
    val md_theme_light_secondary = Color(0xFF51606F)
    val md_theme_light_onSecondary = Color(0xFFFFFFFF)
    val md_theme_light_secondaryContainer = Color(0xFFD4E4F6)
    val md_theme_light_onSecondaryContainer = Color(0xFF0D1D2A)
    val md_theme_light_tertiary = Color(0xFF67587A)
    val md_theme_light_onTertiary = Color(0xFFFFFFFF)
    val md_theme_light_tertiaryContainer = Color(0xFFEDDCFF)
    val md_theme_light_onTertiaryContainer = Color(0xFF221534)
    val md_theme_light_error = Color(0xFFBA1A1A)
    val md_theme_light_errorContainer = Color(0xFFFFDAD6)
    val md_theme_light_onError = Color(0xFFFFFFFF)
    val md_theme_light_onErrorContainer = Color(0xFF410002)
    val md_theme_light_background = Color(0xFFFCFCFF)
    val md_theme_light_onBackground = Color(0xFF1A1C1E)
    val md_theme_light_surface = Color(0xFFFCFCFF)
    val md_theme_light_onSurface = Color(0xFF1A1C1E)
    val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
    val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
    val md_theme_light_outline = Color(0xFF72787E)
    val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
    val md_theme_light_inverseSurface = Color(0xFF2F3133)
    val md_theme_light_inversePrimary = Color(0xFF92CCFF)
    val md_theme_light_shadow = Color(0xFF000000)
    val md_theme_light_surfaceTint = Color(0xFF006397)
    val md_theme_light_outlineVariant = Color(0xFFC2C7CE)
    val md_theme_light_scrim = Color(0xFF000000)

    val md_theme_dark_primary = Color(0xFF92CCFF)
    val md_theme_dark_onPrimary = Color(0xFF003351)
    val md_theme_dark_primaryContainer = Color(0xFF004B73)
    val md_theme_dark_onPrimaryContainer = Color(0xFFCCE5FF)
    val md_theme_dark_secondary = Color(0xFFB8C8DA)
    val md_theme_dark_onSecondary = Color(0xFF23323F)
    val md_theme_dark_secondaryContainer = Color(0xFF394857)
    val md_theme_dark_onSecondaryContainer = Color(0xFFD4E4F6)
    val md_theme_dark_tertiary = Color(0xFFD1BFE7)
    val md_theme_dark_onTertiary = Color(0xFF372A4A)
    val md_theme_dark_tertiaryContainer = Color(0xFF4E4162)
    val md_theme_dark_onTertiaryContainer = Color(0xFFEDDCFF)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF1A1C1E)
    val md_theme_dark_onBackground = Color(0xFFE2E2E5)
    val md_theme_dark_surface = Color(0xFF1A1C1E)
    val md_theme_dark_onSurface = Color(0xFFE2E2E5)
    val md_theme_dark_surfaceVariant = Color(0xFF42474E)
    val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CE)
    val md_theme_dark_outline = Color(0xFF8C9198)
    val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
    val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
    val md_theme_dark_inversePrimary = Color(0xFF006397)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFF92CCFF)
    val md_theme_dark_outlineVariant = Color(0xFF42474E)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFF006498)


}